In [10]:
import numpy as np
import random

In [11]:
print("I love you mani")

I love you mani


In [12]:
import numpy as np
print(np.__version__)

1.19.2


In [13]:
## step-1: finding out the allowed positions

row = [0,1,2,3,4,5]
col = [0,1,2,3,4,5,6]

start_matrix = np.array([2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,0 ,2.63,2.63,0 ,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,0 ,2.63,2.63,0 ,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63]).reshape(6,7)

def allowed_path(i,j):
    main_path = []
    

            
    ## westside
    path = []
    if ((j == 0 and i >=0) or (i == 1 and j == 2) or (i == 1 and j == 5) or (i == 3 and j == 2) or (i == 3 and j == 5)):
        path.append(1)
    else:
        path.append(0)
    ## Northside
    if ((i==0 and j >=0) or (i==2 and j== 1) or (i == 2 and j == 4) or (i == 4 and j == 1) or (i == 4 and j == 4)):
        path.append(1)
    else:
        path.append(0)
     ## Eastside:
    if ( (i == 1 and j == 0) or (i == 1 and j == 3) or (i>=0 and j == 6) or (i == 3 and j == 0) or (i == 3 and j == 3) ):
        path.append(1)
    else:
        path.append(0)
    ## Southside
    if ((i == 0 and j == 1) or (i == 0 and j == 4) or (i == 2 and j == 1) or (i == 2 and j== 4) or (i== 5 and j>=0)   ):
        path.append(1)
    else:
        path.append(0)
    #             print(i,j)
    return path



start_matrix = np.array([2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,0 ,2.63,2.63,0 ,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,0 ,2.63,2.63,0 ,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63]).reshape(6,7)

## step-2: Sensor, finding out the location based on the given evidence:

def sensor_evidence (evidence_path):
    P_Obstable_not_detect = 0.2
    P_Obstacle_Detect = 0.8
    P_Open_Sq_Obstacle = 0.15
    P_Open_Sq_Open_Sq = 0.85
    
    

    next_path = evidence_path
    # next_path = [0,0,0,0]

    row = [0,1,2,3,4,5]
    col = [0,1,2,3,4,5,6]

    total_prob_onecell = []
    #actual_path = allowed_path(i,j)
    # actual_path = allowed_path(0,1)
    # print(actual_path)

    sum_sensor_all_direction = []



    for i in [0,1,2,3,4,5]:
        for j in [0,1,2,3,4,5,6] :
    #         sum_sensor_all_direction = 0
            actual_path = allowed_path(i,j)



            total_prob_all_dir = []
            prob_percell_all_dir = []
            if ((i == 1 and j == 1) or (i==1 and j ==4) or (i==3 and j ==1 ) or (i==3 and j==4)):
                prob_percell_all_dir.append(0)

            else:
                for k in [0,1,2,3]:
                    if (actual_path[k]== 0 and next_path[k]==0):
                        prob_percell_all_dir.append(0.85)
                    if (actual_path[k]== 1 and next_path[k]==0):
                        prob_percell_all_dir.append(0.2)
                    if (actual_path[k]== 0 and next_path[k]==1):
                        prob_percell_all_dir.append(0.15)
                    if (actual_path[k]== 1 and next_path[k]==1):
                        prob_percell_all_dir.append(0.8)
            ########print(i, j, prob_percell_all_dir, start_matrix[i,j])

            total_prob_all_dir = ((np.prod(prob_percell_all_dir) * start_matrix[i,j]).round(5))

    #         sum_sensor_all_direction = sum_sensor_all_direction + int(sensor_all_direction)

            sum_sensor_all_direction.append(total_prob_all_dir)


    sensor_probability = []
    for value in sum_sensor_all_direction:
        sensor_probability.append((value*100/np.sum(sum_sensor_all_direction)).round(2))
    Evidence_Probability = sensor_probability

    Evidence_matrix = np.matrix(Evidence_Probability).reshape(6,7)
    return Evidence_matrix
    
    
    

## Step-3: Finding out the Prediction for next step.. based on the previous state


def moving_north(previous_evidence):
    row = [1,2,3,4,5,6]
    col = [1,2,3,4,5,6,7]
    
#     Evidence_matrix = sensor_evidence(previous_evidence)

    motion_prob_allcells = []
    for i in [0,1,2,3,4,5]:
        for j in [0,1,2,3,4,5,6]:
#             print('i,j = ',i,j)
            if ((i==1 and j==1) or (i==1 and j==4) or (i==3 and j==1) or (i==3 and j==4)):
                motion_prob_onecell = 0
                #####print(motion_prob_onecell)
                motion_prob_allcells.append(motion_prob_onecell)
                continue
            else:

                prob_calculation = []
                next_paths = []
                nextt = ()

                # p_w = Evidence_matrix[i,j-1]
                # p_n = Evidence_matrix[i-1,j]
                # p_e = Evidence_matrix[i1,j+1]
                # p_s = Evidence_matrix[i+1,j]


                ## get the target positions 
                ## from West
                 # if boundary
                if (i in range(0,7) and j-1 < 0)  or (i==1 and j-1==1) or (i==1 and j-1==4) or(i==3 and j-1==1) or (i==3 and j-1==4): 
                    nextt =(i,j)
                # if not a boundary
                elif (i in range(0,7) and j-1>=0 ):
                    nextt = (i, j-1)
                next_paths.append(nextt)

                ## from North
                if (i in range(0,6) and j in range(0,7)):
                    nextt = (i,j)
                # elif(i-1>=0 and j in range(0,7)):
                next_paths.append(nextt)

                ## from east
                if (i in range(0,7) and j+1>=7) or (i==1 and j+1==1) or (i==1 and j+1==4) or(i==3 and j+1==1) or (i==3 and j+1==4):
                    nextt = (i,j)
                elif(i in range(0,7) and j+1<=6):
                    nextt=(i,j+1)
                next_paths.append(nextt)

                ## from south
                if(i+1>=6 and j in range(0,7)) or (i+1==3 and j==4) or (i+1==3 and j==1) or (i+1==1 and j==1) or (i+1==1 and j==4):
                    nextt = (i,j)
                elif(i+1<6 and j in range(0,7)) and (i<=5 and j in range(0,7)):
                    nextt = (i+1,j)
                next_paths.append(nextt)


                ### get the target values
                target_prob = []

                ## from west
                if (i in range(0,7) ):
                    target_prob.append(0.1)
                ## from North
                # 
                if (i==0 and j in range(0,7)) or (i-1==1 and j ==1) or (i-1==1 and j==4) or(i-1==3 and j==1) or (i-1==3 and j==4):
                    target_prob.append(0.8)
                else:
                    target_prob.append(0)
                ## from east
                if(i in range(0,7)):
                    target_prob.append(0.1)
                ## from south
                # or (i+1==3 and j==4) or (i+1==3 and j==1) or (i+1==1 and j==1) or (i+1==1 and j==4)
                if(i==5 and j in range(0,7)) or (i+1==3 and j==4) or (i+1==3 and j==1) or (i+1==1 and j==1) or (i+1==1 and j==4):
                    target_prob.append(0)
                else:
                    target_prob.append(0.8)



                Evidence_matrix[next_paths[0][0],next_paths[0][1]]
                motion_prob_onecell = 0
            for k in [0,1,2,3]:
                motion_prob_onecell = ((motion_prob_onecell+ Evidence_matrix[next_paths[k][0],next_paths[k][1]] * target_prob[k]).round(3))
            motion_prob_allcells.append(motion_prob_onecell)
            #####print('motion_prob_onecell: ',motion_prob_onecell)
#             
    motion_prob = np.matrix(motion_prob_allcells).reshape(6,7)
    start_matrix = motion_prob
    return start_matrix


## step-3: def moving_west(previous_evidence):

def moving_west(previous_evidence):
    motion_prob_allcells = []
    for i in [0,1,2,3,4,5]:
        for j in [0,1,2,3,4,5,6]:
#             print('i,j = ',i,j)
            if ((i==1 and j==1) or (i==1 and j==4) or (i==3 and j==1) or (i==3 and j==4)):
                motion_prob_onecell = 0
                #######print(motion_prob_onecell)
                motion_prob_allcells.append(motion_prob_onecell)
                continue
            else:

                prob_calculation = []
                next_paths = []
                nextt = ()

                # p_w = Evidence_matrix[i,j-1]
                # p_n = Evidence_matrix[i-1,j]
                # p_e = Evidence_matrix[i1,j+1]
                # p_s = Evidence_matrix[i+1,j]


                ## get the target positions 
                ## from West
                 # if boundary
                if(i in range(0,7) and j in range(0,7)):
                    nextt=(i,j)
                next_paths.append(nextt)

    ## from North
                if (j in range (0,7) and i-1<0) or (i-1==1 and j==1) or (i-1==1 and j==4) or (i-1==3 and j==1) or (i-1==3 and j==4):
                    nextt=(i,j)
                elif(i-1>=0 and j in range(0,7)):
                    nextt=(i-1,j)
                next_paths.append(nextt)

    ## from East
                if (i in range(0,7) and j+1>6) or(i==1 and j+1==1) or (i==1 and j+1==4) or(i==3 and j+1==1) or(i==3 and j+1==4):
                    nextt=(i,j)
                else:
                    nextt=(i,j+1)
                next_paths.append(nextt)

    ## from South
                if(i+1>5 and j in range(0,7)) or(i+1==1 and j==1)or(i+1==1 and j==4)or(i+1==3 and j==1)or(i+1==3 and j==4):
                    nextt = (i,j)
                else:
                    nextt=(i+1,j)
                next_paths.append(nextt)


                ### get the target values
                target_prob = []

                ## from West
                if (i in range (0,7) and j-1<0) or (i==1 and j-1==1)or(i==1 and j-1==4)or(i==3 and j-1==1)or(i==3 and j-1==4):
                    target_prob.append(0.8)
                else:
                    target_prob.append(0)

                ## from North
                if (i in range(0,7)):
                    target_prob.append(0.1)
                # else:
                #     target_prob.append(0)

                ## from east
                if (i in range(0,7) and j+1>6) or(i==1 and j+1 ==1) or(i==1 and j+1==4) or(i==3 and j+1==1) or(i==3 and j+1==4):
                    target_prob.append(0)
                else:
                    target_prob.append(0.8)

                ## from south
                # or (i+1==3 and j==4) or (i+1==3 and j==1) or (i+1==1 and j==1) or (i+1==1 and j==4)
                if(i in range(0,7)):
                    target_prob.append(0.1)


                #######print(next_paths)

                #######print(target_prob)



                Evidence_matrix[next_paths[0][0],next_paths[0][1]]
                motion_prob_onecell = 0
            for k in [0,1,2,3]:
                motion_prob_onecell = ((motion_prob_onecell+ Evidence_matrix[next_paths[k][0],next_paths[k][1]] * target_prob[k]).round(3))
            motion_prob_allcells.append(motion_prob_onecell.round(2))
            #######print('motion_prob_onecell: ',motion_prob_onecell)
            #######print('---------------------------------------------')

    motion_prob = np.matrix(motion_prob_allcells).reshape(6,7)
    start_matrix = motion_prob

    # output = f"{num:.9f}"   (float("{:.8f}".format(float(motion_prob_onecell))))
    return start_matrix


## Sensing: [0, 0, 0, 0]

In [14]:
start_matrix = np.array([2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,0 ,2.63,2.63,0 ,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,0 ,2.63,2.63,0 ,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63,
                           2.63,2.63,2.63,2.63,2.63,2.63,2.63]).reshape(6,7)
sensor_evidence([0,0,0,0] )

matrix([[0.47, 0.47, 2.01, 2.01, 0.47, 2.01, 0.47],
        [0.47, 0.  , 2.01, 2.01, 0.  , 2.01, 2.01],
        [2.01, 0.47, 8.53, 8.53, 0.47, 8.53, 2.01],
        [0.47, 0.  , 2.01, 2.01, 0.  , 2.01, 2.01],
        [2.01, 2.01, 8.53, 8.53, 2.01, 8.53, 2.01],
        [0.47, 2.01, 2.01, 2.01, 2.01, 2.01, 0.47]])

## Moving: N

In [15]:
Evidence_matrix = sensor_evidence([0,0,0,0])
start_matrix = moving_north([0,0,0,0])
start_matrix

matrix([[0.846, 0.624, 3.464, 3.464, 0.778, 3.31 , 2.232],
        [1.702, 0.   , 7.226, 7.226, 0.   , 7.226, 2.01 ],
        [0.624, 1.43 , 2.508, 2.508, 2.082, 1.856, 2.662],
        [1.702, 0.   , 7.226, 7.226, 0.   , 7.226, 2.01 ],
        [0.778, 4.27 , 2.662, 2.662, 4.922, 2.01 , 1.43 ],
        [0.248, 0.248, 0.402, 0.402, 0.402, 0.248, 0.248]])

## Sensing: [1, 0, 0, 0]

In [16]:
start_matrix = moving_north([0,0,0,0])
sensor_evidence([1,0,0,0] )

matrix([[5.500e-01, 2.000e-02, 4.200e-01, 4.200e-01, 2.000e-02,
         4.100e-01, 6.000e-02],
        [1.110e+00, 0.000e+00, 2.005e+01, 8.800e-01, 0.000e+00,
         2.005e+01, 2.500e-01],
        [1.730e+00, 4.000e-02, 1.310e+00, 1.310e+00, 6.000e-02,
         9.700e-01, 3.300e-01],
        [1.110e+00, 0.000e+00, 2.005e+01, 8.800e-01, 0.000e+00,
         2.005e+01, 2.500e-01],
        [2.160e+00, 5.200e-01, 1.390e+00, 1.390e+00, 6.000e-01,
         1.050e+00, 1.800e-01],
        [1.600e-01, 3.000e-02, 5.000e-02, 5.000e-02, 5.000e-02,
         3.000e-02, 1.000e-02]])

## Moving: N

In [17]:
Evidence_matrix = sensor_evidence([1,0,0,0])
start_matrix = moving_north([1,0,0,0])
start_matrix

matrix([[1.3850e+00, 1.1300e-01, 1.6420e+01, 1.0840e+00, 9.9000e-02,
         1.6376e+01, 2.9500e-01],
        [1.6060e+00, 0.0000e+00, 3.1410e+00, 3.1410e+00, 0.0000e+00,
         2.8060e+00, 2.2940e+00],
        [1.0650e+00, 3.3600e-01, 1.6175e+01, 8.4100e-01, 2.7600e-01,
         1.6079e+01, 3.3000e-01],
        [1.9500e+00, 0.0000e+00, 3.2050e+00, 3.2050e+00, 0.0000e+00,
         2.8700e+00, 2.1740e+00],
        [3.9600e-01, 7.9500e-01, 2.3100e-01, 2.3900e-01, 7.6400e-01,
         1.0200e-01, 1.3100e-01],
        [1.9000e-02, 2.1000e-02, 8.0000e-03, 1.0000e-02, 8.0000e-03,
         6.0000e-03, 4.0000e-03]])

## Sensing: [0, 0, 0, 0]

In [18]:
start_matrix = moving_north([1,0,0,0])
sensor_evidence([0,0,0,0] )

matrix([[1.600e-01, 1.000e-02, 8.020e+00, 5.300e-01, 1.000e-02,
         8.000e+00, 3.000e-02],
        [1.800e-01, 0.000e+00, 1.530e+00, 1.530e+00, 0.000e+00,
         1.370e+00, 1.120e+00],
        [5.200e-01, 4.000e-02, 3.357e+01, 1.750e+00, 3.000e-02,
         3.337e+01, 1.600e-01],
        [2.200e-01, 0.000e+00, 1.570e+00, 1.570e+00, 0.000e+00,
         1.400e+00, 1.060e+00],
        [1.900e-01, 3.900e-01, 4.800e-01, 5.000e-01, 3.700e-01,
         2.100e-01, 6.000e-02],
        [0.000e+00, 1.000e-02, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00]])

## Moving: W

In [19]:
Evidence_matrix = sensor_evidence([0,0,0,0])
start_matrix = moving_west([0,0,0,0])
start_matrix


matrix([[1.700e-01, 6.420e+00, 1.380e+00, 2.100e-01, 6.400e+00,
         9.600e-01, 1.200e-01],
        [2.100e-01, 0.000e+00, 6.610e+00, 2.300e-01, 0.000e+00,
         6.130e+00, 2.000e-02],
        [4.900e-01, 2.686e+01, 1.710e+00, 3.300e-01, 2.670e+01,
         4.000e-01, 2.200e-01],
        [2.500e-01, 0.000e+00, 5.920e+00, 2.200e-01, 0.000e+00,
         5.330e+00, 2.000e-02],
        [4.900e-01, 4.200e-01, 5.600e-01, 4.500e-01, 2.000e-01,
         1.900e-01, 1.100e-01],
        [3.000e-02, 4.000e-02, 5.000e-02, 5.000e-02, 4.000e-02,
         2.000e-02, 1.000e-02]])

## Sensing: [0, 1, 0, 1]

In [20]:
start_matrix = moving_west([0,0,0,0])
sensor_evidence([0,1,0,1] )

matrix([[1.000e-02, 9.530e+00, 3.800e-01, 6.000e-02, 9.500e+00,
         2.700e-01, 1.000e-02],
        [0.000e+00, 0.000e+00, 8.000e-02, 0.000e+00, 0.000e+00,
         8.000e-02, 0.000e+00],
        [1.000e-02, 3.987e+01, 9.000e-02, 2.000e-02, 3.963e+01,
         2.000e-02, 0.000e+00],
        [0.000e+00, 0.000e+00, 7.000e-02, 0.000e+00, 0.000e+00,
         7.000e-02, 0.000e+00],
        [1.000e-02, 1.200e-01, 3.000e-02, 2.000e-02, 6.000e-02,
         1.000e-02, 0.000e+00],
        [0.000e+00, 1.000e-02, 1.000e-02, 1.000e-02, 1.000e-02,
         1.000e-02, 0.000e+00]])

## Sensing: [0, 1, 0, 1]

In [21]:
Evidence_matrix = sensor_evidence([0,1,0,1])
start_matrix = moving_west([0,1,0,1])
start_matrix

matrix([[7.63e+00, 2.21e+00, 9.00e-02, 7.61e+00, 2.12e+00, 4.00e-02,
         0.00e+00],
        [0.00e+00, 0.00e+00, 1.10e-01, 1.00e-02, 0.00e+00, 9.00e-02,
         0.00e+00],
        [3.19e+01, 8.05e+00, 3.00e-02, 3.17e+01, 7.94e+00, 2.00e-02,
         0.00e+00],
        [0.00e+00, 0.00e+00, 7.00e-02, 0.00e+00, 0.00e+00, 6.00e-02,
         0.00e+00],
        [1.00e-01, 4.00e-02, 2.00e-02, 5.00e-02, 2.00e-02, 1.00e-02,
         0.00e+00],
        [1.00e-02, 2.00e-02, 1.00e-02, 1.00e-02, 2.00e-02, 0.00e+00,
         0.00e+00]])

## Sensing: [1, 0, 0, 0]

In [22]:
start_matrix = moving_west([0,1,0,1])
sensor_evidence([1,0,0,0] )

matrix([[4.420e+00, 6.000e-02, 1.000e-02, 8.300e-01, 5.000e-02,
         0.000e+00, 0.000e+00],
        [0.000e+00, 0.000e+00, 2.700e-01, 0.000e+00, 0.000e+00,
         2.200e-01, 0.000e+00],
        [7.847e+01, 2.100e-01, 1.000e-02, 1.462e+01, 2.000e-01,
         1.000e-02, 0.000e+00],
        [0.000e+00, 0.000e+00, 1.700e-01, 0.000e+00, 0.000e+00,
         1.500e-01, 0.000e+00],
        [2.500e-01, 0.000e+00, 1.000e-02, 2.000e-02, 0.000e+00,
         0.000e+00, 0.000e+00],
        [1.000e-02, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00]])